version: '3.8'
services:
  nest-app:
    build:
      context: .
    ports:
      - '8080:4000'
    volumes:
      - my_volume:/app/data
    environment:
      - PORT=4000
    command: ['yarn', 'start:prod']
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3322
      - POSTGRES_DB=fn2
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  my_volume:
  postgres_volume:
