name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "hello" > file.txt
      - name: checking
        run: cat file.txt
