name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
      - name: deploy
        run: echo "${SSH_KEY}" > my_ssh_key.pem |
          chmod -i 400 my_ssh_key.pem
          ssh -i my_ssh_key.pem ${SERVER_USER}@${SERVER_HOST}
