name: Deploy to Server
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./app
jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
      - name: deploy
        run: echo "${SSH_KEY}" > my_ssh_key.pem |
          chmod 400 my_ssh_key.pem
          ssh -i my_ssh_key.pem -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST}
          git pull origin main
          sudo docker compose down
          sudo docker compose up -d --build
